/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/browser/pw-tools-core.interactions.ts
/**
 * Playwright-backed browser interaction tools, including clicks, form input,
 * screenshots, batch actions, and SSRF-aware post-interaction navigation checks.
 */
import { resolveNonNegativeIntegerOption } from "../../../../shim/number-runtime.js";
import { normalizeOptionalString } from "../../../../shim/string-coerce-runtime.js";
import type { Frame, Page } from "playwright-core";
import { formatErrorMessage } from "../infra/errors.js";
import type { SsrFPolicy } from "../infra/net/ssrf.js";
import {
  ACT_MAX_BATCH_ACTIONS,
  ACT_MAX_BATCH_DEPTH,
  ACT_MAX_CLICK_DELAY_MS,
  ACT_MAX_WAIT_TIME_MS,
  resolveActInteractionTimeoutMs,
  resolveActWaitTimeoutMs,
} from "./act-policy.js";
import type { BrowserActRequest, BrowserFormField } from "./client-actions.types.js";
import { normalizeBrowserEvaluateFunctionSource } from "./evaluate-source.js";
import { DEFAULT_FILL_FIELD_TYPE } from "./form-fields.js";
import {
  assertBrowserNavigationResultAllowed,
  type BrowserNavigationPolicyOptions,
  withBrowserNavigationPolicy,
} from "./navigation-guard.js";
import { resolveStrictExistingUploadPaths } from "./paths.js";
import {
  assertPageNavigationCompletedSafely,
  closeBlockedNavigationTarget,
  createObservedDialogAbortSignalForPage,
  ensurePageState,
  forceDisconnectPlaywrightForTarget,
  getPageForTargetId,
  isBrowserObservedDialogBlockedError,
  markObservedDialogsHandledRemotelyForPage,
  quarantineTargetWithoutClosing,
  refLocator,
  restoreRoleRefsForTarget,
} from "./pw-session.js";
import {
  normalizeTimeoutMs,
  requireRef,
  requireRefOrSelector,
  toAIFriendlyError,
} from "./pw-tools-core.shared.js";
import { closePageViaPlaywright, resizeViewportViaPlaywright } from "./pw-tools-core.snapshot.js";
import {
  ANNOTATION_MAX_LABELS_DEFAULT,
  type AnnotationItem,
  buildOverlayClearScript,
  buildOverlayInjectionScript,
  type CoordinateSpace,
  planAnnotations,
  type RawAnnotationInput,
} from "./screenshot-annotate.js";

type TargetOpts = {
  cdpUrl: string;
  targetId?: string;
};

const INTERACTION_NAVIGATION_GRACE_MS = 250;

// Bounds for draining the popup chain after an interaction. The queue is
// adversarial — validating a popup can append another — so it needs a ceiling
// on both count and wall-clock, or a page that opens one popup per grace
// window keeps the action (and every serialized call behind it) alive forever.
const POPUP_CHAIN_MAX_VALIDATIONS = 32;
const POPUP_CHAIN_DRAIN_BUDGET_MS = 5_000;
// Quarantining the overflow needs its own bounds: an unresponsive close() must
// not keep the action pending any more than an endless popup chain may.
const POPUP_CHAIN_MAX_CLOSES = 256;
const POPUP_CHAIN_CLOSE_BUDGET_MS = 2_000;

// The one message the host matches on to distrust the whole route
// (`mentionsUntornDownBrowser` in external-chrome-backend.ts). Every path that
// fails to contain a page must report exactly this, or the host keeps serving
// a route whose pages are still live.
const UNTORN_DOWN_BROWSER_MESSAGE =
  "Navigation blocked: popup chain exceeded the validation budget and the browser could not be torn down; unvalidated pages may still be live";

type NavigationObservablePage = Pick<Page, "url"> & {
  mainFrame?: () => Frame;
  on?: (event: "framenavigated", listener: (frame: Frame) => void) => unknown;
  off?: (event: "framenavigated", listener: (frame: Frame) => void) => unknown;
};

const pendingInteractionNavigationGuardCleanup = new WeakMap<Page, () => void>();

function resolveBoundedDelayMs(value: number | undefined, label: string, maxMs: number): number {
  const normalized = Math.floor(value ?? 0);
  if (!Number.isFinite(normalized) || normalized < 0) {
    throw new Error(`${label} must be >= 0`);
  }
  if (normalized > maxMs) {
    throw new Error(`${label} exceeds maximum of ${maxMs}ms`);
  }
  return normalized;
}

async function getRestoredPageForTarget(opts: TargetOpts) {
  const page = await getPageForTargetId(opts);
  ensurePageState(page);
  restoreRoleRefsForTarget({ cdpUrl: opts.cdpUrl, targetId: opts.targetId, page });
  return page;
}

function toFriendlyInteractionError(err: unknown, label: string): Error {
  return isBrowserObservedDialogBlockedError(err) ? err : toAIFriendlyError(err, label);
}

function reconcileRemoteDialogAfterActionSettled(page: Page, signal?: AbortSignal): void {
  if (isBrowserObservedDialogBlockedError(signal?.reason)) {
    markObservedDialogsHandledRemotelyForPage(page);
  }
}

const resolveInteractionTimeoutMs = resolveActInteractionTimeoutMs;

// Returns true only when the URL change indicates a cross-document navigation
// (i.e., a real network fetch occurred). Same-document hash-only mutations —
// anchor clicks and history.pushState/replaceState that change only the
// fragment — do not cause a network request and must not trigger SSRF checks.
function didCrossDocumentUrlChange(page: { url(): string }, previousUrl: string): boolean {
  const currentUrl = page.url();
  if (currentUrl === previousUrl) {
    return false;
  }
  try {
    const prev = new URL(previousUrl);
    const curr = new URL(currentUrl);
    if (
      prev.origin === curr.origin &&
      prev.pathname === curr.pathname &&
      prev.search === curr.search
    ) {
      // Only the fragment changed — same-document navigation, no fetch.
      return false;
    }
  } catch {
    // Non-parseable URL; fall through to string comparison.
  }
  return true;
}

// Returns true when a framenavigated event represents only a hash-only
// same-document mutation (no network request). Used in event-driven checks
// where the event itself is the navigation signal — unlike URL polling, we
// cannot use identical URLs as a "no navigation" sentinel because same-URL
// reloads and form submits also fire framenavigated with an unchanged URL.
function isHashOnlyNavigation(currentUrl: string, previousUrl: string): boolean {
  if (currentUrl === previousUrl) {
    // Exact same URL + framenavigated firing = reload or form submit, not a
    // fragment hop. Must run SSRF checks.
    return false;
  }
  try {
    const prev = new URL(previousUrl);
    const curr = new URL(currentUrl);
    return (
      prev.origin === curr.origin && prev.pathname === curr.pathname && prev.search === curr.search
    );
  } catch {
    return false;
  }
}

function isMainFrameNavigation(page: NavigationObservablePage, frame: Frame): boolean {
  if (typeof page.mainFrame !== "function") {
    return true;
  }
  return frame === page.mainFrame();
}

async function assertSubframeNavigationAllowed(
  frameUrl: string,
  ssrfPolicy?: SsrFPolicy,
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"],
): Promise<void> {
  if (
    (!ssrfPolicy && !browserProxyMode) ||
    (!frameUrl.startsWith("http://") && !frameUrl.startsWith("https://"))
  ) {
    // Non-network frame URLs like about:blank and about:srcdoc do not cross the
    // browser SSRF boundary, so they should not trigger the navigation policy.
    return;
  }

  await assertBrowserNavigationResultAllowed({
    url: frameUrl,
    ...withBrowserNavigationPolicy(ssrfPolicy, { browserProxyMode }),
  });
}

type ObservedDelayedNavigations = {
  mainFrameNavigated: boolean;
  subframes: string[];
};

function snapshotNetworkFrameUrl(frame: Frame): string | null {
  try {
    const frameUrl = frame.url();
    return frameUrl.startsWith("http://") || frameUrl.startsWith("https://") ? frameUrl : null;
  } catch {
    return null;
  }
}

async function assertObservedDelayedNavigations(opts: {
  cdpUrl: string;
  page: Page;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  targetId?: string;
  observed: ObservedDelayedNavigations;
}): Promise<void> {
  let subframeError: unknown;
  try {
    for (const frameUrl of opts.observed.subframes) {
      await assertSubframeNavigationAllowed(
        frameUrl,
        opts.ssrfPolicy,
        opts.browserProxyMode,
      );
    }
  } catch (err) {
    subframeError = err;
  }
  if (opts.observed.mainFrameNavigated) {
    await assertPageNavigationCompletedSafely({
      cdpUrl: opts.cdpUrl,
      page: opts.page,
      response: null,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  }
  if (subframeError) {
    throw toLintErrorObject(subframeError, "Non-Error thrown");
  }
}

function observeDelayedInteractionNavigation(
  page: NavigationObservablePage,
  previousUrl: string,
): Promise<ObservedDelayedNavigations> {
  if (didCrossDocumentUrlChange(page, previousUrl)) {
    return Promise.resolve({ mainFrameNavigated: true, subframes: [] });
  }
  if (typeof page.on !== "function" || typeof page.off !== "function") {
    return Promise.resolve({ mainFrameNavigated: false, subframes: [] });
  }

  return new Promise<ObservedDelayedNavigations>((resolve) => {
    const subframes: string[] = [];
    const onFrameNavigated = (frame: Frame) => {
      if (!isMainFrameNavigation(page, frame)) {
        const frameUrl = snapshotNetworkFrameUrl(frame);
        if (frameUrl) {
          subframes.push(frameUrl);
        }
        return;
      }
      // Use isHashOnlyNavigation rather than !didCrossDocumentUrlChange: the
      // event firing is itself the navigation signal, so a same-URL reload must
      // not be treated as "no navigation" the way URL polling would.
      if (isHashOnlyNavigation(page.url(), previousUrl)) {
        return;
      }
      cleanup();
      resolve({ mainFrameNavigated: true, subframes });
    };
    const timeout = setTimeout(() => {
      cleanup();
      resolve({
        mainFrameNavigated: didCrossDocumentUrlChange(page, previousUrl),
        subframes,
      });
    }, INTERACTION_NAVIGATION_GRACE_MS);
    const cleanup = () => {
      clearTimeout(timeout);
      // Call off directly on page (not via a cached reference) to preserve
      // Playwright's EventEmitter `this` binding.
      page.off!("framenavigated", onFrameNavigated);
    };

    // Call on directly on page (not via a cached reference) to preserve
    // Playwright's EventEmitter `this` binding.
    page.on!("framenavigated", onFrameNavigated);
  });
}

function scheduleDelayedInteractionNavigationGuard(opts: {
  cdpUrl: string;
  page: Page;
  previousUrl: string;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  targetId?: string;
}): Promise<void> {
  if (!opts.ssrfPolicy && !opts.browserProxyMode) {
    return Promise.resolve();
  }
  const page = opts.page as unknown as NavigationObservablePage;
  if (didCrossDocumentUrlChange(page, opts.previousUrl)) {
    return assertPageNavigationCompletedSafely({
      cdpUrl: opts.cdpUrl,
      page: opts.page,
      response: null,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  }
  if (typeof page.on !== "function" || typeof page.off !== "function") {
    return Promise.resolve();
  }

  pendingInteractionNavigationGuardCleanup.get(opts.page)?.();

  return new Promise<void>((resolve, reject) => {
    const settle = (err?: unknown) => {
      cleanup();
      if (err) {
        reject(toLintErrorObject(err, "Non-Error rejection"));
        return;
      }
      resolve();
    };
    const subframes: string[] = [];
    const onFrameNavigated = (frame: Frame) => {
      if (!isMainFrameNavigation(page, frame)) {
        const frameUrl = snapshotNetworkFrameUrl(frame);
        if (frameUrl) {
          subframes.push(frameUrl);
        }
        return;
      }
      // Use isHashOnlyNavigation rather than !didCrossDocumentUrlChange: the
      // event firing is itself the navigation signal, so a same-URL reload must
      // not be treated as "no navigation" the way URL polling would.
      if (isHashOnlyNavigation(page.url(), opts.previousUrl)) {
        return;
      }
      cleanup();
      void assertObservedDelayedNavigations({
        cdpUrl: opts.cdpUrl,
        page: opts.page,
        ssrfPolicy: opts.ssrfPolicy,
        browserProxyMode: opts.browserProxyMode,
        targetId: opts.targetId,
        observed: { mainFrameNavigated: true, subframes },
      }).then(() => settle(), settle);
    };
    const timeout = setTimeout(() => {
      cleanup();
      void assertObservedDelayedNavigations({
        cdpUrl: opts.cdpUrl,
        page: opts.page,
        ssrfPolicy: opts.ssrfPolicy,
        browserProxyMode: opts.browserProxyMode,
        targetId: opts.targetId,
        observed: {
          mainFrameNavigated: didCrossDocumentUrlChange(page, opts.previousUrl),
          subframes,
        },
      }).then(() => settle(), settle);
    }, INTERACTION_NAVIGATION_GRACE_MS);
    const cleanup = () => {
      clearTimeout(timeout);
      page.off!("framenavigated", onFrameNavigated);
      if (pendingInteractionNavigationGuardCleanup.get(opts.page) === settle) {
        pendingInteractionNavigationGuardCleanup.delete(opts.page);
      }
    };

    pendingInteractionNavigationGuardCleanup.set(opts.page, settle);
    page.on!("framenavigated", onFrameNavigated);
  });
}

async function assertInteractionNavigationCompletedSafely<T>(opts: {
  action: () => Promise<T>;
  cdpUrl: string;
  page: Page;
  previousUrl: string;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  targetId?: string;
}): Promise<T> {
  if (!opts.ssrfPolicy && !opts.browserProxyMode) {
    return await opts.action();
  }
  // Phase 1: keep a framenavigated listener alive for the entire duration of the
  // action so navigations triggered mid-click or mid-evaluate are not missed.
  // Using a fixed pre-action timer would expire before the action finishes for
  // slow interactions, silently bypassing the SSRF guard.
  const navPage = opts.page as unknown as NavigationObservablePage;
  const pageContext = (
    opts.page as unknown as {
      context?: () => { on?: (event: string, listener: (page: Page) => void) => void; off?: (event: string, listener: (page: Page) => void) => void; close?: () => Promise<void>; browser?: () => { close?: () => Promise<void> } | undefined };
    }
  ).context?.();
  const popupsDuringAction: Page[] = [];
  // The context is PERSISTENT and shared with the user, who can open tabs at
  // any moment — as can any unrelated producer. The page event fires for all of
  // them, so tracking every new page would let the drain below validate, and on
  // denial CLOSE, a tab the user opened themselves; a busy stream of them could
  // even escalate to tearing down the whole context. Only pages that descend
  // from the page being acted on are ours to police.
  //
  // opener() is async and this listener must stay synchronous (an await here
  // would drop events), so kick the probe off on arrival and record the answer;
  // consumers below wait for the probe of the page they are about to touch.
  const openerOfPopup = new Map<unknown, unknown>();
  const popupOwnershipProbe = new Map<unknown, Promise<void>>();
  const popupOwnershipPending = new Set<unknown>();
  const onContextPage = (newPage: Page) => {
    popupsDuringAction.push(newPage);
    const opener = (newPage as unknown as { opener?: () => Promise<Page | null> }).opener;
    if (typeof opener !== "function") return;
    popupOwnershipPending.add(newPage);
    popupOwnershipProbe.set(
      newPage,
      Promise.resolve()
        .then(() => opener.call(newPage))
        .then(
          (parent) => {
            if (parent) openerOfPopup.set(newPage, parent);
          },
          () => undefined,
        )
        .then(() => {
          popupOwnershipPending.delete(newPage);
        }),
    );
  };
  /**
   * Whether this page's lineage question has been ANSWERED yet. A pending probe
   * is not the same as "not ours": treating it that way would let a popup the
   * action opened slip past the cleanup below, unvalidated and still live.
   */
  const ownershipAnswered = (page: unknown): boolean => !popupOwnershipPending.has(page);
  /**
   * Settle outstanding lineage probes, re-checking after every round: a popup
   * can open a child while we await, and that child's probe is registered after
   * any snapshot we took, so a single allSettled would never wait for it.
   * Bounded by the caller's deadline so an unresponsive page cannot hold the
   * action — and the serialized stop/quit behind it — open.
   */
  const settleOwnershipProbes = async (deadline: Promise<void>): Promise<void> => {
    let expired = false;
    void deadline.then(() => {
      expired = true;
    });
    while (!expired && popupOwnershipPending.size > 0) {
      const outstanding = [...popupOwnershipPending]
        .map((page) => popupOwnershipProbe.get(page))
        .filter((probe): probe is Promise<void> => probe !== undefined);
      if (outstanding.length === 0) return;
      await Promise.race([Promise.allSettled(outstanding), deadline]);
    }
  };
  /**
   * Whether a page's opener chain reaches the page being acted on. Walks the
   * chain so a popup opened BY a popup still counts as ours, and is bounded so
   * a cycle or an absurdly deep chain cannot hang the drain.
   *
   * Fails closed toward the USER's data: a page whose lineage we could not
   * establish is treated as not ours, so it is never validated and never
   * closed. Anything the action itself opened does report an opener.
   */
  const descendsFromActedPage = (page: unknown): boolean => {
    let cursor = page;
    for (let hops = 0; hops < POPUP_CHAIN_MAX_VALIDATIONS; hops += 1) {
      const parent = openerOfPopup.get(cursor);
      if (parent === undefined) return false;
      if (parent === opts.page) return true;
      cursor = parent;
    }
    return false;
  };
  if (pageContext && typeof pageContext.on === "function") {
    pageContext.on("page", onContextPage);
  }
  let navigatedDuringAction = false;
  const subframeNavigationsDuringAction: string[] = [];
  const onFrameNavigated = (frame: Frame) => {
    if (!isMainFrameNavigation(navPage, frame)) {
      const frameUrl = snapshotNetworkFrameUrl(frame);
      if (frameUrl) {
        subframeNavigationsDuringAction.push(frameUrl);
      }
      return;
    }
    // Use isHashOnlyNavigation rather than didCrossDocumentUrlChange: the event
    // firing is the navigation signal, so a same-URL reload must not be skipped
    // the way it would be by URL-equality polling.
    if (!isHashOnlyNavigation(opts.page.url(), opts.previousUrl)) {
      navigatedDuringAction = true;
    }
  };
  if (typeof navPage.on === "function") {
    navPage.on("framenavigated", onFrameNavigated);
  }

  let result: T | undefined;
  let actionError: unknown = null;
  try {
    result = await opts.action();
  } catch (err) {
    actionError = err;
  } finally {
    if (typeof navPage.off === "function") {
      navPage.off("framenavigated", onFrameNavigated);
    }
  }

  const navigationObserved =
    navigatedDuringAction || didCrossDocumentUrlChange(opts.page, opts.previousUrl);

  let subframeError: unknown;
  try {
    for (const frameUrl of subframeNavigationsDuringAction) {
      await assertSubframeNavigationAllowed(
        frameUrl,
        opts.ssrfPolicy,
        opts.browserProxyMode,
      );
    }
  } catch (err) {
    subframeError = err;
  }

  let navigationError: unknown;
  try {
  if (navigationObserved) {
    await assertPageNavigationCompletedSafely({
      cdpUrl: opts.cdpUrl,
      page: opts.page,
      response: null,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  } else if (actionError) {
    // Preserve the action-error path semantics: if a rejected click/evaluate still
    // triggers a delayed navigation, the SSRF block must win over the original
    // action error instead of surfacing a stale interaction failure.
    const observed = await observeDelayedInteractionNavigation(opts.page, opts.previousUrl);
    if (observed.mainFrameNavigated || observed.subframes.length > 0) {
      await assertObservedDelayedNavigations({
        cdpUrl: opts.cdpUrl,
        page: opts.page,
        ssrfPolicy: opts.ssrfPolicy,
        browserProxyMode: opts.browserProxyMode,
        targetId: opts.targetId,
        observed,
      });
    }
  } else {
    // Successful interactions still need a short grace window: a click can resolve
    // before the navigation event fires, and a blocked late hop must be observable
    // to the current caller instead of only quarantining the page in the background.
    await scheduleDelayedInteractionNavigationGuard({
      cdpUrl: opts.cdpUrl,
      page: opts.page,
      previousUrl: opts.previousUrl,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  }

  } catch (err) {
    navigationError = err;
  }
  // NOTE: the context listener stays attached across popup validation below —
  // a popup can open a further popup inside its own grace window, and
  // detaching here would leave that second-generation tab uncollected and
  // unvalidated (in direct mode nothing else would catch it).
  let popupError: unknown;
  // Shared last-resort teardown for pages we could not contain individually.
  // Both the per-popup close failure and the overflow path escalate through
  // this, so a stuck page has exactly one ladder: context close, then browser
  // close.
  //
  // Only a resolved CONTEXT close proves containment from in here: its pages
  // are gone with it. A resolved BROWSER close proves only that the call
  // returned — the process can still be alive with pages running, and nothing
  // in this runtime can observe process exit. So browser close reports
  // "unproven" and the caller raises the untorn-down signal, which is what
  // makes the host run its own verified process teardown.
  const tearDownUncontainedPages = async (
    deadline?: Promise<void>,
  ): Promise<"contained" | "unproven"> => {
    const closeContext = (
      pageContext as unknown as { close?: () => Promise<void> } | undefined
    )?.close;
    if (typeof closeContext === "function") {
      const contextClosed = await Promise.race([
        Promise.resolve()
          .then(() => closeContext.call(pageContext))
          .then(
            () => true,
            () => false,
          ),
        // A caller that already burned its budget passes no deadline: racing a
        // fired one would resolve instantly and prove nothing.
        deadline
          ? deadline.then(() => false)
          : new Promise<boolean>((resolve) => {
              const timer = setTimeout(() => resolve(false), POPUP_CHAIN_CLOSE_BUDGET_MS);
              (timer as unknown as { unref?: () => void }).unref?.();
            }),
      ]);
      if (contextClosed) return "contained";
    }
    // The context would not close (rejected, or still not settled at the
    // deadline), so live pages that were never validated survive and the
    // listener is about to detach. Every per-page and per-context remedy has
    // now failed, so try the browser. Give this its own budget.
    const browserOf = (
      pageContext as unknown as { browser?: () => { close?: () => Promise<void> } | undefined }
        | undefined
    )?.browser;
    const browser = typeof browserOf === "function" ? browserOf.call(pageContext) : undefined;
    if (!browser || typeof browser.close !== "function") return "unproven";
    await Promise.race([
      Promise.resolve()
        .then(() => browser.close?.())
        .then(
          () => undefined,
          () => undefined,
        ),
      new Promise<void>((resolve) => {
        const timer = setTimeout(resolve, POPUP_CHAIN_CLOSE_BUDGET_MS);
        (timer as unknown as { unref?: () => void }).unref?.();
      }),
    ]);
    // Deliberately NOT reporting success on a resolved close: the host owns
    // process teardown and must verify the exit itself.
    return "unproven";
  };
  try {
    // Drain the chain rather than a snapshot: validating a popup can append
    // more entries to popupsDuringAction, so index forward as it grows.
    //
    // BOUNDED, because the queue is adversarial: each iteration awaits a
    // ~250ms grace window, so a page that opens one popup per window appends
    // at least as fast as this drains and the loop never empties. That would
    // hang the action forever — and the backend serializes every browser call,
    // so a later stop (and dispose at quit) would queue behind it indefinitely.
    // On overrun, stop validating and CLOSE the remainder: leaving them live
    // would be the unvalidated-tab bug this drain exists to prevent.
    const drainDeadline = Date.now() + POPUP_CHAIN_DRAIN_BUDGET_MS;
    let popupIndex = 0;
    for (
      ;
      popupIndex < popupsDuringAction.length
      && popupIndex < POPUP_CHAIN_MAX_VALIDATIONS
      && Date.now() < drainDeadline;
      popupIndex += 1
    ) {
      const popupPage = popupsDuringAction[popupIndex]!;
      // Wait for this page's lineage answer, then skip anything PROVEN not to
      // be ours: validating it could quarantine or close one of the user's own
      // tabs, which is strictly worse than not policing a page we never opened.
      // A page that never answered is not proven either way, so it stays in
      // scope here and the overflow cleanup below decides its fate.
      await popupOwnershipProbe.get(popupPage);
      if (ownershipAnswered(popupPage) && !descendsFromActedPage(popupPage)) continue;
      // Per popup, not around the loop: a denial on the first popup must not
      // leave later ones unvalidated and selectable on a denied URL. Keep the
      // first error and keep going.
      try {
        // A popup starts at about:blank; reuse the delayed-navigation observer
        // so a still-loading popup gets the same grace window before
        // validation, and a policy deny quarantines/closes the popup target
        // like any other block.
        const observedPopup = await observeDelayedInteractionNavigation(
          popupPage as unknown as NavigationObservablePage,
          "about:blank",
        );
        await assertObservedDelayedNavigations({
          cdpUrl: opts.cdpUrl,
          page: popupPage,
          ssrfPolicy: opts.ssrfPolicy,
          browserProxyMode: opts.browserProxyMode,
          observed: observedPopup,
        });
      } catch (err) {
        if (popupError === undefined) popupError = err;
        // Fail closed on the rejected popup itself. A policy deny above only
        // quarantines — assertPageNavigationCompletedSafely never closes; that
        // step belongs to callers that own the navigation lifecycle — and this
        // popup was created BY the action, not by the user, so it is ours to
        // tear down. Left open, the denied page keeps executing after the
        // context listener detaches (in direct mode no lifetime request gate
        // remains to catch it).
        //
        // Bounded, because close() can hang forever on an adversarial page.
        // But a timeout is NOT success: the page is still live and scriptable.
        // Escalate exactly like the overflow path — context, then browser —
        // and if none of that works, report the untorn-down browser so the
        // host distrusts the route instead of returning an ordinary denial.
        await Promise.race([
          closeBlockedNavigationTarget({
            cdpUrl: opts.cdpUrl,
            page: popupPage as Page,
          }).then(
            () => undefined,
            () => undefined,
          ),
          new Promise<void>((resolve) => {
            const timer = setTimeout(resolve, POPUP_CHAIN_CLOSE_BUDGET_MS);
            (timer as unknown as { unref?: () => void }).unref?.();
          }),
        ]);
        // Ask the PAGE whether it closed, rather than trusting the call to have
        // reported it. closeBlockedNavigationTarget swallows page.close()
        // rejections internally (pw-session.ts), so it resolves even when the
        // page refused to go — reading its resolution as success would silently
        // skip the escalation for exactly the pages that need it. A page that
        // cannot answer isClosed() has not proven anything either, so it counts
        // as uncontained too.
        const isClosed = (popupPage as { isClosed?: () => boolean }).isClosed;
        const popupClosed = typeof isClosed === "function" && isClosed.call(popupPage) === true;
        if (!popupClosed && (await tearDownUncontainedPages()) !== "contained") {
          popupError = new Error(UNTORN_DOWN_BROWSER_MESSAGE);
          break;
        }
      }
    }
    // Settle outstanding lineage probes before the sweep below: it runs
    // synchronously (so pending page events can still enqueue) and must be able
    // to tell our popups from the user's without awaiting per page. Bounded on
    // its own budget, and repeated internally so a child popup that arrives
    // mid-await is waited on too.
    const ownershipDeadline = new Promise<void>((resolve) => {
      const timer = setTimeout(resolve, POPUP_CHAIN_CLOSE_BUDGET_MS);
      (timer as unknown as { unref?: () => void }).unref?.();
    });
    await settleOwnershipProbes(ownershipDeadline);
    // A page whose probe never answered counts as OURS. Once the budget above
    // is spent the browser is already failing to answer, and dropping such a
    // page would mean the listener detaches with an unvalidated, never-closed
    // popup and no untorn-down signal for the host — silently
    // losing containment. The user's genuinely own tabs answer opener() with
    // null promptly, so they are still excluded.
    const isOursOrUnanswered = (page: unknown): boolean =>
      descendsFromActedPage(page) || !ownershipAnswered(page);
    const ownedPagesRemain = (): boolean => {
      for (let i = popupIndex; i < popupsDuringAction.length; i += 1) {
        if (isOursOrUnanswered(popupsDuringAction[i]!)) return true;
      }
      return false;
    };
    if (ownedPagesRemain()) {
      // Quarantine must be bounded too, for the same reason the drain above is:
      // a burst of popups, or one unresponsive close(), would otherwise keep
      // this action — and the serialized stop/quit cleanup behind it — pending
      // indefinitely. Close concurrently under a single deadline rather than
      // serially awaiting each one, and re-read the queue (not a snapshot) so
      // popups appended while these closes run are quarantined too.
      const closeDeadline = new Promise<void>((resolve) => {
        const timer = setTimeout(resolve, POPUP_CHAIN_CLOSE_BUDGET_MS);
        // Do not hold the process open on this timer.
        (timer as unknown as { unref?: () => void }).unref?.();
      });
      const closing: Array<Promise<void>> = [];
      let deadlineReached = false;
      void closeDeadline.then(() => { deadlineReached = true; });
      // Outer loop so newly-arrived popups are picked up: the inner loop never
      // awaits, so on its own it drains the queue as it stands and returns
      // before the event loop can deliver another page event. Yielding
      // between sweeps is what actually lets the queue grow and be re-read;
      // without it a popup created during cleanup would be left live,
      // unvalidated and unquarantined once the listener detaches.
      while (
        !deadlineReached
        && popupIndex < popupsDuringAction.length
        && closing.length < POPUP_CHAIN_MAX_CLOSES
      ) {
        for (
          ;
          popupIndex < popupsDuringAction.length
          && closing.length < POPUP_CHAIN_MAX_CLOSES;
          popupIndex += 1
        ) {
          const unvalidated = popupsDuringAction[popupIndex]!;
          // A page that arrived mid-sweep may not have answered opener() yet.
          // Do NOT advance past it: this index only moves forward, so skipping
          // it here would strand an action-created popup that proves ours a
          // moment later — unvalidated, unquarantined, and invisible to
          // ownedPagesRemain(). Stop the sweep instead; the yield below lets
          // the probe settle and the outer loop retries the same page, all
          // still under closeDeadline.
          if (!ownershipAnswered(unvalidated)) break;
          // Same boundary as the drain: the user's own tabs are not ours to
          // quarantine or close, however far behind this cleanup falls.
          if (!descendsFromActedPage(unvalidated)) continue;
          // Quarantine BEFORE closing, and do not make it conditional on the
          // close succeeding: close() can hang forever on an adversarial page,
          // and when the deadline below fires we would otherwise leave a live,
          // never-validated popup selectable — in direct mode there is no
          // lifetime CDP request gate to catch it afterwards. Marking is
          // synchronous bookkeeping, so it completes regardless.
          closing.push(
            quarantineTargetWithoutClosing({
              cdpUrl: opts.cdpUrl,
              page: unvalidated as Page,
            })
              .catch(() => undefined)
              .then(() => (unvalidated as { close?: () => Promise<void> }).close?.())
              .then(
                () => undefined,
                () => undefined,
              ),
          );
        }
        // Hand control back so pending page events can enqueue, then re-check.
        // Racing the deadline keeps this bounded even against a page that
        // appends a new popup on every turn.
        await Promise.race([
          new Promise<void>((resolve) => {
            const timer = setTimeout(resolve, 0);
            (timer as unknown as { unref?: () => void }).unref?.();
          }),
          closeDeadline,
        ]);
      }
      // Never await a popup's close() unbounded: a hung page must not outrank
      // returning from the interaction.
      //
      // Track whether they actually finished. popupIndex only records that a
      // close was ISSUED, and quarantine is bookkeeping that never closes a
      // page (see quarantineTargetWithoutClosing), so a fully-drained queue
      // whose closes all hang would otherwise look fully handled while every
      // one of those popups is still live and scriptable.
      const allClosesSettled = await Promise.race([
        Promise.all(closing).then(() => true),
        closeDeadline.then(() => false),
      ]);
      // If the bounds cut us off with popups still unaccounted for, they were
      // neither validated nor quarantined and the listener is about to detach —
      // in direct mode nothing else would ever check them. Per-page cleanup has
      // already failed to keep up here, so fail closed on the whole context
      // rather than leaving live, never-validated pages behind.
      if (ownedPagesRemain() || !allClosesSettled) {
        // Nothing reachable from this process can shut the browser down, and a
        // resolved close() would only prove the call returned, not that the
        // process exited. Say so explicitly rather than reporting a generic
        // policy denial: the host owns process teardown and must treat this
        // route as untrusted until it verifies an exit itself.
        if ((await tearDownUncontainedPages(closeDeadline)) !== "contained") {
          popupError = new Error(UNTORN_DOWN_BROWSER_MESSAGE);
        }
      }
      if (popupError === undefined) {
        popupError = new Error(
          "Navigation blocked: popup chain exceeded the validation budget; remaining popups were closed",
        );
      }
    }
  } finally {
    // Always detach: a throw here would otherwise leak the listener, retaining
    // every tab opened afterwards for the life of the context.
    if (pageContext && typeof pageContext.off === "function") {
      pageContext.off("page", onContextPage);
    }
  }

  // A containment failure outranks EVERYTHING. Ordinary denials describe a
  // request that was refused — the safe outcome. This one says pages we never
  // validated are still live and could not be torn down, and it is the only
  // signal the host uses to distrust the route. If a denied main-frame
  // navigation happened in the same interaction (easy for an adversarial page
  // to arrange), reporting that instead would leave the route usable while
  // those pages keep running.
  if (popupError && /could not be torn down/.test(String((popupError as Error)?.message ?? ""))) {
    throw toLintErrorObject(popupError, "Non-Error thrown");
  }

  // Otherwise policy denials outrank the action's own error, and the main-frame
  // denial outranks subframe/popup denials, so the caller sees the navigation it
  // asked for being refused. All were still evaluated above.
  if (navigationError) {
    throw toLintErrorObject(navigationError, "Non-Error thrown");
  }

  if (subframeError) {
    throw toLintErrorObject(subframeError, "Non-Error thrown");
  }

  if (popupError) {
    throw toLintErrorObject(popupError, "Non-Error thrown");
  }

  if (actionError) {
    throw toLintErrorObject(actionError, "Non-Error thrown");
  }
  return result as T;
}

async function awaitActionWithAbort<T>(
  actionPromise: Promise<T>,
  abortPromise?: Promise<never>,
  onActionResolvedAfterAbort?: () => void,
): Promise<T> {
  if (!abortPromise) {
    return await actionPromise;
  }
  try {
    return await Promise.race([actionPromise, abortPromise]);
  } catch (err) {
    // If abort wins the race, the action may reject later; avoid unhandled rejections.
    void actionPromise.then(
      () => onActionResolvedAfterAbort?.(),
      () => {},
    );
    throw err;
  }
}

function createAbortPromise(signal?: AbortSignal): {
  abortPromise?: Promise<never>;
  cleanup: () => void;
} {
  return createAbortPromiseWithListener(signal);
}

function createAbortPromiseWithListener(
  signal?: AbortSignal,
  onAbort?: (reason: unknown) => void,
): {
  abortPromise?: Promise<never>;
  cleanup: () => void;
} {
  if (!signal) {
    return { cleanup: () => {} };
  }
  let abortListener: (() => void) | undefined;
  const abortPromise: Promise<never> = signal.aborted
    ? (() => {
        onAbort?.(signal.reason);
        return Promise.reject(
          toLintErrorObject(signal.reason ?? new Error("aborted"), "Non-Error rejection"),
        );
      })()
    : new Promise((_, reject) => {
        abortListener = () => {
          onAbort?.(signal.reason);
          reject(toLintErrorObject(signal.reason ?? new Error("aborted"), "Non-Error rejection"));
        };
        signal.addEventListener("abort", abortListener, { once: true });
      });
  // Avoid unhandled rejections on early returns.
  void abortPromise.catch(() => {});
  return {
    abortPromise,
    cleanup: () => {
      if (abortListener) {
        signal.removeEventListener("abort", abortListener);
      }
    },
  };
}
/** Highlights a role ref in the target page for visual inspection. */
export async function highlightViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  ref: string;
}): Promise<void> {
  const page = await getRestoredPageForTarget(opts);
  const ref = requireRef(opts.ref);
  try {
    await refLocator(page, ref).highlight();
  } catch (err) {
    throw toFriendlyInteractionError(err, ref);
  }
}

/** Clicks or double-clicks a role ref or selector with dialog and navigation guards. */
export async function clickViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  ref?: string;
  selector?: string;
  doubleClick?: boolean;
  button?: "left" | "right" | "middle";
  modifiers?: Array<"Alt" | "Control" | "ControlOrMeta" | "Meta" | "Shift">;
  delayMs?: number;
  timeoutMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const resolved = requireRefOrSelector(opts.ref, opts.selector);
  const page = await getRestoredPageForTarget(opts);
  const label = resolved.ref ?? resolved.selector!;
  const locator = resolved.ref
    ? refLocator(page, requireRef(resolved.ref))
    : page.locator(resolved.selector!);
  const timeout = resolveInteractionTimeoutMs(opts.timeoutMs);
  const previousUrl = page.url();
  const signal = opts.signal;
  let abortListener: (() => void) | undefined;
  let abortReject: ((reason: unknown) => void) | undefined;
  let abortPromise: Promise<never> | undefined;
  if (signal) {
    abortPromise = new Promise((_, reject) => {
      abortReject = reject;
    });
    void abortPromise.catch(() => {});
    const disconnect = () => {
      if (isBrowserObservedDialogBlockedError(signal.reason)) {
        return;
      }
      void forceDisconnectPlaywrightForTarget({
        cdpUrl: opts.cdpUrl,
        targetId: opts.targetId,
        ssrfPolicy: opts.ssrfPolicy,
        reason: "click aborted",
      }).catch(() => {});
    };
    if (signal.aborted) {
      disconnect();
      throw signal.reason ?? new Error("aborted");
    }
    abortListener = () => {
      disconnect();
      abortReject?.(signal.reason ?? new Error("aborted"));
    };
    signal.addEventListener("abort", abortListener, { once: true });
    if (signal.aborted) {
      abortListener();
      throw signal.reason ?? new Error("aborted");
    }
  }
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, signal);
  try {
    await assertInteractionNavigationCompletedSafely({
      action: async () => {
        const delayMs = resolveBoundedDelayMs(
          opts.delayMs,
          "click delayMs",
          ACT_MAX_CLICK_DELAY_MS,
        );
        if (delayMs > 0) {
          await awaitActionWithAbort(
            locator.hover({ timeout }),
            abortPromise,
            reconcileRemoteDialog,
          );
          await new Promise((resolve) => {
            setTimeout(resolve, delayMs);
          });
        }
        if (opts.doubleClick) {
          await awaitActionWithAbort(
            locator.dblclick({
              timeout,
              button: opts.button,
              modifiers: opts.modifiers,
            }),
            abortPromise,
            reconcileRemoteDialog,
          );
          return;
        }
        await awaitActionWithAbort(
          locator.click({
            timeout,
            button: opts.button,
            modifiers: opts.modifiers,
          }),
          abortPromise,
          reconcileRemoteDialog,
        );
      },
      cdpUrl: opts.cdpUrl,
      page,
      previousUrl,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  } catch (err) {
    throw toFriendlyInteractionError(err, label);
  } finally {
    if (signal && abortListener) {
      signal.removeEventListener("abort", abortListener);
    }
  }
}

/** Clicks absolute page coordinates with optional double-click and navigation guard. */
export async function clickCoordsViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  x: number;
  y: number;
  doubleClick?: boolean;
  button?: "left" | "right" | "middle";
  delayMs?: number;
  timeoutMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const page = await getRestoredPageForTarget(opts);
  const previousUrl = page.url();
  const { abortPromise, cleanup } = createAbortPromise(opts.signal);
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, opts.signal);
  await assertInteractionNavigationCompletedSafely({
    action: async () => {
      await awaitActionWithAbort(
        page.mouse.click(opts.x, opts.y, {
          button: opts.button,
          clickCount: opts.doubleClick ? 2 : 1,
          delay: resolveBoundedDelayMs(opts.delayMs, "clickCoords delayMs", ACT_MAX_CLICK_DELAY_MS),
        }),
        abortPromise,
        reconcileRemoteDialog,
      );
    },
    cdpUrl: opts.cdpUrl,
    page,
    previousUrl,
    ssrfPolicy: opts.ssrfPolicy,
    browserProxyMode: opts.browserProxyMode,
    targetId: opts.targetId,
  }).finally(cleanup);
}

/** Hovers a role ref or selector on the target page. */
export async function hoverViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  ref?: string;
  selector?: string;
  timeoutMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const resolved = requireRefOrSelector(opts.ref, opts.selector);
  const page = await getRestoredPageForTarget(opts);
  const label = resolved.ref ?? resolved.selector!;
  const locator = resolved.ref
    ? refLocator(page, requireRef(resolved.ref))
    : page.locator(resolved.selector!);
  const previousUrl = page.url();
  const { abortPromise, cleanup } = createAbortPromise(opts.signal);
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, opts.signal);
  try {
    await assertInteractionNavigationCompletedSafely({
      action: async () => {
        await awaitActionWithAbort(
          locator.hover({
            timeout: resolveInteractionTimeoutMs(opts.timeoutMs),
          }),
          abortPromise,
          reconcileRemoteDialog,
        );
      },
      cdpUrl: opts.cdpUrl,
      page,
      previousUrl,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  } catch (err) {
    throw toFriendlyInteractionError(err, label);
  } finally {
    cleanup();
  }
}

/** Drags from one role ref or selector to another. */
export async function dragViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  startRef?: string;
  startSelector?: string;
  endRef?: string;
  endSelector?: string;
  timeoutMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const resolvedStart = requireRefOrSelector(opts.startRef, opts.startSelector);
  const resolvedEnd = requireRefOrSelector(opts.endRef, opts.endSelector);
  const page = await getRestoredPageForTarget(opts);
  const startLocator = resolvedStart.ref
    ? refLocator(page, requireRef(resolvedStart.ref))
    : page.locator(resolvedStart.selector!);
  const endLocator = resolvedEnd.ref
    ? refLocator(page, requireRef(resolvedEnd.ref))
    : page.locator(resolvedEnd.selector!);
  const startLabel = resolvedStart.ref ?? resolvedStart.selector!;
  const endLabel = resolvedEnd.ref ?? resolvedEnd.selector!;
  const previousUrl = page.url();
  const { abortPromise, cleanup } = createAbortPromise(opts.signal);
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, opts.signal);
  try {
    await assertInteractionNavigationCompletedSafely({
      action: async () => {
        await awaitActionWithAbort(
          startLocator.dragTo(endLocator, {
            timeout: resolveInteractionTimeoutMs(opts.timeoutMs),
          }),
          abortPromise,
          reconcileRemoteDialog,
        );
      },
      cdpUrl: opts.cdpUrl,
      page,
      previousUrl,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  } catch (err) {
    throw toFriendlyInteractionError(err, `${startLabel} -> ${endLabel}`);
  } finally {
    cleanup();
  }
}

/** Selects one or more option values on a select-like element. */
export async function selectOptionViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  ref?: string;
  selector?: string;
  values: string[];
  timeoutMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const resolved = requireRefOrSelector(opts.ref, opts.selector);
  if (!opts.values?.length) {
    throw new Error("values are required");
  }
  const page = await getRestoredPageForTarget(opts);
  const label = resolved.ref ?? resolved.selector!;
  const locator = resolved.ref
    ? refLocator(page, requireRef(resolved.ref))
    : page.locator(resolved.selector!);
  const previousUrl = page.url();
  const { abortPromise, cleanup } = createAbortPromise(opts.signal);
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, opts.signal);
  try {
    await assertInteractionNavigationCompletedSafely({
      action: async () => {
        await awaitActionWithAbort(
          locator.selectOption(opts.values, {
            timeout: resolveInteractionTimeoutMs(opts.timeoutMs),
          }),
          abortPromise,
          reconcileRemoteDialog,
        );
      },
      cdpUrl: opts.cdpUrl,
      page,
      previousUrl,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  } catch (err) {
    throw toFriendlyInteractionError(err, label);
  } finally {
    cleanup();
  }
}

/** Presses a keyboard key against a ref, selector, or focused page. */
export async function pressKeyViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  key: string;
  delayMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const key = normalizeOptionalString(opts.key) ?? "";
  if (!key) {
    throw new Error("key is required");
  }
  const page = await getPageForTargetId(opts);
  ensurePageState(page);
  const previousUrl = page.url();
  const { abortPromise, cleanup } = createAbortPromise(opts.signal);
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, opts.signal);
  try {
    await assertInteractionNavigationCompletedSafely({
      action: async () => {
        await awaitActionWithAbort(
          page.keyboard.press(key, {
            delay: resolveNonNegativeIntegerOption(opts.delayMs, 0),
          }),
          abortPromise,
          reconcileRemoteDialog,
        );
      },
      cdpUrl: opts.cdpUrl,
      page,
      previousUrl,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  } finally {
    cleanup();
  }
}

/** Types text into a ref, selector, or focused page. */
export async function typeViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  ref?: string;
  selector?: string;
  text: string;
  submit?: boolean;
  slowly?: boolean;
  timeoutMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const resolved = requireRefOrSelector(opts.ref, opts.selector);
  const text = opts.text ?? "";
  const page = await getRestoredPageForTarget(opts);
  const label = resolved.ref ?? resolved.selector!;
  const locator = resolved.ref
    ? refLocator(page, requireRef(resolved.ref))
    : page.locator(resolved.selector!);
  const timeout = resolveInteractionTimeoutMs(opts.timeoutMs);
  const { abortPromise, cleanup } = createAbortPromise(opts.signal);
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, opts.signal);
  try {
    const previousUrl = page.url();
    if (opts.slowly) {
      await assertInteractionNavigationCompletedSafely({
        action: async () => {
          await awaitActionWithAbort(
            locator.click({ timeout }),
            abortPromise,
            reconcileRemoteDialog,
          );
          await awaitActionWithAbort(
            locator.type(text, { timeout, delay: 75 }),
            abortPromise,
            reconcileRemoteDialog,
          );
          if (opts.submit) {
            await awaitActionWithAbort(
              locator.press("Enter", { timeout }),
              abortPromise,
              reconcileRemoteDialog,
            );
          }
        },
        cdpUrl: opts.cdpUrl,
        page,
        previousUrl,
        ssrfPolicy: opts.ssrfPolicy,
        browserProxyMode: opts.browserProxyMode,
        targetId: opts.targetId,
      });
    } else {
      await assertInteractionNavigationCompletedSafely({
        action: async () => {
          await awaitActionWithAbort(
            locator.fill(text, { timeout }),
            abortPromise,
            reconcileRemoteDialog,
          );
          if (opts.submit) {
            await awaitActionWithAbort(
              locator.press("Enter", { timeout }),
              abortPromise,
              reconcileRemoteDialog,
            );
          }
        },
        cdpUrl: opts.cdpUrl,
        page,
        previousUrl,
        ssrfPolicy: opts.ssrfPolicy,
        browserProxyMode: opts.browserProxyMode,
        targetId: opts.targetId,
      });
    }
  } catch (err) {
    throw toFriendlyInteractionError(err, label);
  } finally {
    cleanup();
  }
}

/** Fills multiple form fields with per-field selector/ref/type support. */
export async function fillFormViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  fields: BrowserFormField[];
  timeoutMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const page = await getRestoredPageForTarget(opts);
  const timeout = resolveInteractionTimeoutMs(opts.timeoutMs);
  const { abortPromise, cleanup } = createAbortPromise(opts.signal);
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, opts.signal);
  try {
    for (const field of opts.fields) {
      const ref = field.ref.trim();
      const type = (field.type || DEFAULT_FILL_FIELD_TYPE).trim() || DEFAULT_FILL_FIELD_TYPE;
      const rawValue = field.value;
      const value =
        typeof rawValue === "string"
          ? rawValue
          : typeof rawValue === "number" || typeof rawValue === "boolean"
            ? String(rawValue)
            : "";
      if (!ref) {
        continue;
      }
      const locator = refLocator(page, ref);
      if (type === "checkbox" || type === "radio") {
        const checked =
          rawValue === true || rawValue === 1 || rawValue === "1" || rawValue === "true";
        try {
          const previousUrl = page.url();
          await assertInteractionNavigationCompletedSafely({
            action: async () => {
              await awaitActionWithAbort(
                locator.setChecked(checked, { timeout }),
                abortPromise,
                reconcileRemoteDialog,
              );
            },
            cdpUrl: opts.cdpUrl,
            page,
            previousUrl,
            ssrfPolicy: opts.ssrfPolicy,
            browserProxyMode: opts.browserProxyMode,
            targetId: opts.targetId,
          });
        } catch (err) {
          throw toFriendlyInteractionError(err, ref);
        }
        continue;
      }
      try {
        const previousUrl = page.url();
        await assertInteractionNavigationCompletedSafely({
          action: async () => {
            await awaitActionWithAbort(
              locator.fill(value, { timeout }),
              abortPromise,
              reconcileRemoteDialog,
            );
          },
          cdpUrl: opts.cdpUrl,
          page,
          previousUrl,
          ssrfPolicy: opts.ssrfPolicy,
          browserProxyMode: opts.browserProxyMode,
          targetId: opts.targetId,
        });
      } catch (err) {
        throw toFriendlyInteractionError(err, ref);
      }
    }
  } finally {
    cleanup();
  }
}

/** Evaluates JavaScript in the page after browser action policy validation. */
export async function evaluateViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  fn: string;
  ref?: string;
  timeoutMs?: number;
  signal?: AbortSignal;
}): Promise<unknown> {
  const fnText = normalizeOptionalString(opts.fn) ?? "";
  if (!fnText) {
    throw new Error("function is required");
  }
  const fnSource = normalizeBrowserEvaluateFunctionSource(
    fnText,
    opts.ref ? { argumentName: "el" } : undefined,
  );
  const page = await getRestoredPageForTarget(opts);
  // Clamp evaluate timeout to prevent permanently blocking Playwright's command queue.
  // Without this, a long-running async evaluate blocks all subsequent page operations
  // because Playwright serializes CDP commands per page.
  //
  // NOTE: Playwright's { timeout } on evaluate only applies to installing the function,
  // NOT to its execution time. We must inject a Promise.race timeout into the browser
  // context itself so async functions are bounded.
  const outerTimeout = normalizeTimeoutMs(opts.timeoutMs, 20_000);
  // Leave headroom for routing/serialization overhead so the outer request timeout
  // doesn't fire first and strand a long-running evaluate.
  let evaluateTimeout = Math.max(1000, Math.min(120_000, outerTimeout - 500));
  evaluateTimeout = Math.min(evaluateTimeout, outerTimeout);

  const signal = opts.signal;
  const { abortPromise, cleanup } = createAbortPromiseWithListener(signal, (reason) => {
    if (isBrowserObservedDialogBlockedError(reason)) {
      return;
    }
    void forceDisconnectPlaywrightForTarget({
      cdpUrl: opts.cdpUrl,
      targetId: opts.targetId,
      ssrfPolicy: opts.ssrfPolicy,
      reason: "evaluate aborted",
    }).catch(() => {});
  });
  if (signal?.aborted) {
    throw signal.reason ?? new Error("aborted");
  }

  try {
    const previousUrl = page.url();
    if (opts.ssrfPolicy || opts.browserProxyMode) {
      await assertPageNavigationCompletedSafely({
        cdpUrl: opts.cdpUrl,
        page,
        response: null,
        ssrfPolicy: opts.ssrfPolicy,
        browserProxyMode: opts.browserProxyMode,
        targetId: opts.targetId,
      });
    }

    if (opts.ref) {
      const locator = refLocator(page, opts.ref);
      // eslint-disable-next-line @typescript-eslint/no-implied-eval -- required for browser-context eval
      const elementEvaluator = new Function(
        "el",
        "args",
        `
        "use strict";
        var fnSource = args.fnSource, timeoutMs = args.timeoutMs;
        try {
          var candidate = eval("(" + fnSource + ")");
          if (typeof candidate !== "function") {
            throw new Error("evaluate source did not produce a function");
          }
          var result = candidate(el);
          if (result && typeof result.then === "function") {
            return Promise.race([
              result,
              new Promise(function(_, reject) {
                setTimeout(function() { reject(new Error("evaluate timed out after " + timeoutMs + "ms")); }, timeoutMs);
              })
            ]);
          }
          return result;
        } catch (err) {
          throw new Error("Invalid evaluate function: " + (err && err.message ? err.message : String(err)));
        }
        `,
      ) as (el: Element, args: { fnSource: string; timeoutMs: number }) => unknown;
      const evalPromise = locator.evaluate(elementEvaluator, {
        fnSource,
        timeoutMs: evaluateTimeout,
      });
      const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, signal);
      const result = await assertInteractionNavigationCompletedSafely({
        action: () => awaitActionWithAbort(evalPromise, abortPromise, reconcileRemoteDialog),
        cdpUrl: opts.cdpUrl,
        page,
        previousUrl,
        ssrfPolicy: opts.ssrfPolicy,
        browserProxyMode: opts.browserProxyMode,
        targetId: opts.targetId,
      });
      return result;
    }

    // eslint-disable-next-line @typescript-eslint/no-implied-eval -- required for browser-context eval
    const browserEvaluator = new Function(
      "args",
      `
        "use strict";
        var fnSource = args.fnSource, timeoutMs = args.timeoutMs;
        try {
          var candidate = eval("(" + fnSource + ")");
          if (typeof candidate !== "function") {
            throw new Error("evaluate source did not produce a function");
          }
          var result = candidate();
          if (result && typeof result.then === "function") {
            return Promise.race([
              result,
              new Promise(function(_, reject) {
                setTimeout(function() { reject(new Error("evaluate timed out after " + timeoutMs + "ms")); }, timeoutMs);
              })
            ]);
          }
          return result;
        } catch (err) {
          throw new Error("Invalid evaluate function: " + (err && err.message ? err.message : String(err)));
        }
      `,
    ) as (args: { fnSource: string; timeoutMs: number }) => unknown;
    const evalPromise = page.evaluate(browserEvaluator, {
      fnSource,
      timeoutMs: evaluateTimeout,
    });
    const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, signal);
    const result = await assertInteractionNavigationCompletedSafely({
      action: () => awaitActionWithAbort(evalPromise, abortPromise, reconcileRemoteDialog),
      cdpUrl: opts.cdpUrl,
      page,
      previousUrl,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
    return result;
  } finally {
    cleanup();
  }
}

/** Scrolls a role ref or selector into view. */
export async function scrollIntoViewViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  ref?: string;
  selector?: string;
  timeoutMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const resolved = requireRefOrSelector(opts.ref, opts.selector);
  const page = await getRestoredPageForTarget(opts);
  const timeout = normalizeTimeoutMs(opts.timeoutMs, 20_000);

  const label = resolved.ref ?? resolved.selector!;
  const locator = resolved.ref
    ? refLocator(page, requireRef(resolved.ref))
    : page.locator(resolved.selector!);
  const previousUrl = page.url();
  const { abortPromise, cleanup } = createAbortPromise(opts.signal);
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, opts.signal);
  try {
    await assertInteractionNavigationCompletedSafely({
      action: async () => {
        await awaitActionWithAbort(
          locator.scrollIntoViewIfNeeded({ timeout }),
          abortPromise,
          reconcileRemoteDialog,
        );
      },
      cdpUrl: opts.cdpUrl,
      page,
      previousUrl,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  } catch (err) {
    throw toFriendlyInteractionError(err, label);
  } finally {
    cleanup();
  }
}

/** Waits for load state, timeout, URL, text, ref, or selector conditions. */
export async function waitForViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  timeMs?: number;
  text?: string;
  textGone?: string;
  selector?: string;
  url?: string;
  loadState?: "load" | "domcontentloaded" | "networkidle";
  fn?: string;
  timeoutMs?: number;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<void> {
  const page = await getPageForTargetId(opts);
  ensurePageState(page);
  const timeout = resolveActWaitTimeoutMs(opts.timeoutMs);
  const { abortPromise, cleanup } = createAbortPromise(opts.signal);
  const reconcileRemoteDialog = () => reconcileRemoteDialogAfterActionSettled(page, opts.signal);
  const waitForStep = async <T>(stepPromise: Promise<T>) => {
    await awaitActionWithAbort(stepPromise, abortPromise, reconcileRemoteDialog);
  };

  const previousUrl = page.url();
  try {
    await assertInteractionNavigationCompletedSafely({
      action: async () => {
    if (typeof opts.timeMs === "number" && Number.isFinite(opts.timeMs)) {
      await waitForStep(
        page.waitForTimeout(
          resolveBoundedDelayMs(opts.timeMs, "wait timeMs", ACT_MAX_WAIT_TIME_MS),
        ),
      );
    }
    if (opts.text) {
      await waitForStep(
        page.getByText(opts.text).first().waitFor({
          state: "visible",
          timeout,
        }),
      );
    }
    if (opts.textGone) {
      await waitForStep(
        page.getByText(opts.textGone).first().waitFor({
          state: "hidden",
          timeout,
        }),
      );
    }
    if (opts.selector) {
      const selector = normalizeOptionalString(opts.selector) ?? "";
      if (selector) {
        await waitForStep(page.locator(selector).first().waitFor({ state: "visible", timeout }));
      }
    }
    if (opts.url) {
      const url = normalizeOptionalString(opts.url) ?? "";
      if (url) {
        await waitForStep(page.waitForURL(url, { timeout }));
      }
    }
    if (opts.loadState) {
      await waitForStep(page.waitForLoadState(opts.loadState, { timeout }));
    }
    if (opts.fn) {
      const fn = normalizeOptionalString(opts.fn) ?? "";
      if (fn) {
        await waitForStep(page.waitForFunction(fn, { timeout }));
      }
    }
      },
      cdpUrl: opts.cdpUrl,
      page,
      previousUrl,
      ssrfPolicy: opts.ssrfPolicy,
      browserProxyMode: opts.browserProxyMode,
      targetId: opts.targetId,
    });
  } finally {
    cleanup();
  }
}

/** Captures a screenshot from the target page or element. */
export async function takeScreenshotViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  ref?: string;
  element?: string;
  fullPage?: boolean;
  type?: "png" | "jpeg";
  timeoutMs?: number;
}): Promise<{ buffer: Buffer }> {
  const page = await getPageForTargetId(opts);
  ensurePageState(page);
  restoreRoleRefsForTarget({ cdpUrl: opts.cdpUrl, targetId: opts.targetId, page });
  const type = opts.type ?? "png";
  if (opts.ref) {
    if (opts.fullPage) {
      throw new Error("fullPage is not supported for element screenshots");
    }
    const locator = refLocator(page, opts.ref);
    const buffer = await locator.screenshot({ type, timeout: opts.timeoutMs });
    return { buffer };
  }
  if (opts.element) {
    if (opts.fullPage) {
      throw new Error("fullPage is not supported for element screenshots");
    }
    const locator = page.locator(opts.element).first();
    const buffer = await locator.screenshot({ type, timeout: opts.timeoutMs });
    return { buffer };
  }
  const buffer = await page.screenshot({
    type,
    fullPage: Boolean(opts.fullPage),
    timeout: opts.timeoutMs,
  });
  return { buffer };
}

/** Captures a screenshot with Browser plugin labels over interactive elements. */
export async function screenshotWithLabelsViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  refs: Record<string, { role: string; name?: string; nth?: number }>;
  maxLabels?: number;
  type?: "png" | "jpeg";
  timeoutMs?: number;
  fullPage?: boolean;
  ref?: string;
  element?: string;
}): Promise<{
  buffer: Buffer;
  labels: number;
  skipped: number;
  annotations: AnnotationItem[];
}> {
  const page = await getPageForTargetId(opts);
  ensurePageState(page);
  restoreRoleRefsForTarget({ cdpUrl: opts.cdpUrl, targetId: opts.targetId, page });
  const type = opts.type ?? "png";
  const maxLabels =
    typeof opts.maxLabels === "number" && Number.isFinite(opts.maxLabels)
      ? Math.max(1, Math.floor(opts.maxLabels))
      : ANNOTATION_MAX_LABELS_DEFAULT;

  const refKey = normalizeOptionalString(opts.ref) ?? undefined;
  const elementSelector = normalizeOptionalString(opts.element) ?? undefined;
  const space: CoordinateSpace = opts.fullPage
    ? "fullpage"
    : refKey || elementSelector
      ? "element"
      : "viewport";

  // Read scroll + viewport size. Scroll converts Playwright's viewport-space
  // boundingBoxes into document-space inputs; the viewport size lets the helper
  // restore the shipped `labelsSkipped` semantics by counting off-viewport refs
  // as skipped (in viewport capture mode).
  const view = await page.evaluate(() => ({
    x: window.scrollX || 0,
    y: window.scrollY || 0,
    width: window.innerWidth || 0,
    height: window.innerHeight || 0,
  }));
  const scroll = { x: view.x, y: view.y };

  let elementRect: { x: number; y: number; width: number; height: number } | undefined;
  if (space === "element") {
    const box = await resolveElementBoundingBoxForLabels(page, refKey, elementSelector);
    if (!box) {
      throw new Error(
        `screenshotWithLabelsViaPlaywright: element not found for ${
          refKey ? `ref="${refKey}"` : `selector="${elementSelector ?? ""}"`
        }`,
      );
    }
    // Convert viewport-space bbox to document space.
    elementRect = {
      x: box.x + scroll.x,
      y: box.y + scroll.y,
      width: box.width,
      height: box.height,
    };
  }

  const refKeys = Object.keys(opts.refs ?? {});
  const inputs: RawAnnotationInput[] = [];
  let bboxFailures = 0;
  for (const ref of refKeys) {
    const box = await refLocator(page, ref)
      .boundingBox()
      .catch(() => null);
    if (!box) {
      bboxFailures += 1;
      continue;
    }
    inputs.push({
      ref,
      role: opts.refs[ref].role,
      name: opts.refs[ref].name,
      doc: {
        x: box.x + scroll.x,
        y: box.y + scroll.y,
        width: box.width,
        height: box.height,
      },
    });
  }

  const plan = planAnnotations({
    inputs,
    space,
    scroll,
    viewport: { width: view.width, height: view.height },
    elementRect,
    maxLabels,
  });

  try {
    if (plan.overlayItems.length > 0) {
      const captureY = space === "element" ? elementRect?.y : space === "viewport" ? scroll.y : 0;
      await page.evaluate(buildOverlayInjectionScript({ items: plan.overlayItems, captureY }));
    }
    const buffer =
      space === "element"
        ? await captureElementScreenshotForLabels(
            page,
            refKey,
            elementSelector,
            type,
            opts.timeoutMs,
          )
        : await page.screenshot({
            type,
            fullPage: Boolean(opts.fullPage),
            timeout: opts.timeoutMs,
          });
    return {
      // `labels` reports overlay boxes actually drawn on the captured image
      // (in-viewport, within budget); off-viewport refs are surfaced via
      // `annotations` but not drawn, and are reflected in `skipped`.
      buffer,
      labels: plan.overlayItems.length,
      skipped: plan.skipped + bboxFailures,
      annotations: plan.annotations,
    };
  } finally {
    await page.evaluate(buildOverlayClearScript()).catch(() => {});
  }
}

async function resolveElementBoundingBoxForLabels(
  page: Page,
  refKey: string | undefined,
  cssSelector: string | undefined,
): Promise<{ x: number; y: number; width: number; height: number } | null> {
  if (refKey) {
    try {
      return await refLocator(page, refKey).boundingBox();
    } catch {
      return null;
    }
  }
  if (cssSelector) {
    try {
      return await page.locator(cssSelector).first().boundingBox();
    } catch {
      return null;
    }
  }
  return null;
}

async function captureElementScreenshotForLabels(
  page: Page,
  refKey: string | undefined,
  cssSelector: string | undefined,
  type: "png" | "jpeg",
  timeoutMs: number | undefined,
): Promise<Buffer> {
  if (refKey) {
    return await refLocator(page, refKey).screenshot({ type, timeout: timeoutMs });
  }
  if (cssSelector) {
    return await page.locator(cssSelector).first().screenshot({ type, timeout: timeoutMs });
  }
  throw new Error("captureElementScreenshotForLabels: requires refKey or cssSelector");
}

/** Sets file inputs for a role ref or selector with strict existing-path checks. */
export async function setInputFilesViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  inputRef?: string;
  element?: string;
  paths: string[];
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
}): Promise<void> {
  const page = await getPageForTargetId(opts);
  ensurePageState(page);
  restoreRoleRefsForTarget({ cdpUrl: opts.cdpUrl, targetId: opts.targetId, page });
  if (!opts.paths.length) {
    throw new Error("paths are required");
  }
  const inputRef = normalizeOptionalString(opts.inputRef) ?? "";
  const element = normalizeOptionalString(opts.element) ?? "";
  if (inputRef && element) {
    throw new Error("inputRef and element are mutually exclusive");
  }
  if (!inputRef && !element) {
    throw new Error("inputRef or element is required");
  }

  const locator = inputRef ? refLocator(page, inputRef) : page.locator(element).first();
  const resolvedResult = await resolveStrictExistingUploadPaths({ requestedPaths: opts.paths });
  if (!resolvedResult.ok) {
    throw new Error(resolvedResult.error);
  }
  const resolvedPaths = resolvedResult.paths;

  const previousUrl = page.url();
  await assertInteractionNavigationCompletedSafely({
    action: async () => {
      try {
        await locator.setInputFiles(resolvedPaths);
      } catch (err) {
        throw toFriendlyInteractionError(err, inputRef || element);
      }
      try {
        const handle = await locator.elementHandle();
        if (handle) {
          await handle.evaluate((el) => {
            el.dispatchEvent(new Event("input", { bubbles: true }));
            el.dispatchEvent(new Event("change", { bubbles: true }));
          });
        }
      } catch {
        // Best-effort for sites that don't react to setInputFiles alone.
      }
    },
    cdpUrl: opts.cdpUrl,
    page,
    previousUrl,
    ssrfPolicy: opts.ssrfPolicy,
    browserProxyMode: opts.browserProxyMode,
    targetId: opts.targetId,
  });
}

async function executeSingleAction(
  action: BrowserActRequest,
  cdpUrl: string,
  targetId?: string,
  evaluateEnabled?: boolean,
  ssrfPolicy?: SsrFPolicy,
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"],
  depth = 0,
  signal?: AbortSignal,
): Promise<unknown> {
  if (depth > ACT_MAX_BATCH_DEPTH) {
    throw new Error(`Batch nesting depth exceeds maximum of ${ACT_MAX_BATCH_DEPTH}`);
  }
  const effectiveTargetId = action.targetId ?? targetId;
  switch (action.kind) {
    case "click":
      await clickViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        ref: action.ref,
        selector: action.selector,
        doubleClick: action.doubleClick,
        button: action.button as "left" | "right" | "middle" | undefined,
        modifiers: action.modifiers as Array<
          "Alt" | "Control" | "ControlOrMeta" | "Meta" | "Shift"
        >,
        delayMs: action.delayMs,
        timeoutMs: action.timeoutMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "clickCoords":
      await clickCoordsViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        x: action.x,
        y: action.y,
        doubleClick: action.doubleClick,
        button: action.button as "left" | "right" | "middle" | undefined,
        delayMs: action.delayMs,
        timeoutMs: action.timeoutMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "type":
      await typeViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        ref: action.ref,
        selector: action.selector,
        text: action.text,
        submit: action.submit,
        slowly: action.slowly,
        timeoutMs: action.timeoutMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "press":
      await pressKeyViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        key: action.key,
        delayMs: action.delayMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "hover":
      await hoverViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        ref: action.ref,
        selector: action.selector,
        timeoutMs: action.timeoutMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "scrollIntoView":
      await scrollIntoViewViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        ref: action.ref,
        selector: action.selector,
        timeoutMs: action.timeoutMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "drag":
      await dragViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        startRef: action.startRef,
        startSelector: action.startSelector,
        endRef: action.endRef,
        endSelector: action.endSelector,
        timeoutMs: action.timeoutMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "select":
      await selectOptionViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        ref: action.ref,
        selector: action.selector,
        values: action.values,
        timeoutMs: action.timeoutMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "fill":
      await fillFormViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        fields: action.fields,
        timeoutMs: action.timeoutMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "resize": {
      const resizePage = await getPageForTargetId({ cdpUrl, targetId: effectiveTargetId });
      ensurePageState(resizePage);
      const resizePreviousUrl = resizePage.url();
      await assertInteractionNavigationCompletedSafely({
        action: async () => {
          await resizeViewportViaPlaywright({
            cdpUrl,
            targetId: effectiveTargetId,
            width: action.width,
            height: action.height,
          });
        },
        cdpUrl,
        page: resizePage,
        previousUrl: resizePreviousUrl,
        ssrfPolicy,
        browserProxyMode,
        targetId: effectiveTargetId,
      });
      break;
    }
    case "wait":
      if (action.fn && !evaluateEnabled) {
        throw new Error("wait --fn is disabled by config (browser.evaluateEnabled=false)");
      }
      await waitForViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        timeMs: action.timeMs,
        text: action.text,
        textGone: action.textGone,
        selector: action.selector,
        url: action.url,
        loadState: action.loadState,
        fn: action.fn,
        timeoutMs: action.timeoutMs,
        ssrfPolicy,
        browserProxyMode,
        signal,
      });
      break;
    case "evaluate":
      if (!evaluateEnabled) {
        throw new Error("act:evaluate is disabled by config (browser.evaluateEnabled=false)");
      }
      return await evaluateViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        ssrfPolicy,
        browserProxyMode,
        fn: action.fn,
        ref: action.ref,
        timeoutMs: action.timeoutMs,
        signal,
      });
    case "close":
      await closePageViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
      });
      break;
    case "batch":
      await batchViaPlaywright({
        cdpUrl,
        targetId: effectiveTargetId,
        ssrfPolicy,
        browserProxyMode,
        actions: action.actions,
        stopOnError: action.stopOnError,
        evaluateEnabled,
        depth: depth + 1,
        signal,
      });
      break;
    default:
      throw new Error(`Unsupported batch action kind: ${(action as { kind: string }).kind}`);
  }
  return undefined;
}

/** Executes one high-level browser act request with bounded recursive actions. */
export async function executeActViaPlaywright(opts: {
  cdpUrl: string;
  action: BrowserActRequest;
  targetId?: string;
  evaluateEnabled?: boolean;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  signal?: AbortSignal;
}): Promise<{
  result?: unknown;
  results?: Array<{ ok: boolean; error?: string }>;
  blockedByDialog?: boolean;
  browserState?: unknown;
}> {
  const page = await getPageForTargetId({
    cdpUrl: opts.cdpUrl,
    targetId: opts.targetId,
    ssrfPolicy: opts.ssrfPolicy,
  });
  const dialogAbort = createObservedDialogAbortSignalForPage({
    page,
    parentSignal: opts.signal,
  });
  try {
    if (opts.action.kind === "batch") {
      const batch = await batchViaPlaywright({
        cdpUrl: opts.cdpUrl,
        targetId: opts.targetId,
        ssrfPolicy: opts.ssrfPolicy,
        browserProxyMode: opts.browserProxyMode,
        actions: opts.action.actions,
        stopOnError: opts.action.stopOnError,
        evaluateEnabled: opts.evaluateEnabled,
        signal: dialogAbort.signal,
      });
      return { results: batch.results };
    }
    const result = await executeSingleAction(
      opts.action,
      opts.cdpUrl,
      opts.targetId,
      opts.evaluateEnabled,
      opts.ssrfPolicy,
      opts.browserProxyMode,
      0,
      dialogAbort.signal,
    );
    if (opts.action.kind === "evaluate") {
      return { result };
    }
    return {};
  } catch (err) {
    if (isBrowserObservedDialogBlockedError(err)) {
      return { blockedByDialog: true, browserState: err.browserState };
    }
    throw err;
  } finally {
    dialogAbort.cleanup();
  }
}

/** Executes a bounded sequence of browser actions and returns per-step results. */
export async function batchViaPlaywright(opts: {
  cdpUrl: string;
  targetId?: string;
  actions: BrowserActRequest[];
  stopOnError?: boolean;
  evaluateEnabled?: boolean;
  ssrfPolicy?: SsrFPolicy;
  browserProxyMode?: BrowserNavigationPolicyOptions["browserProxyMode"];
  depth?: number;
  signal?: AbortSignal;
}): Promise<{ results: Array<{ ok: boolean; error?: string }> }> {
  const depth = opts.depth ?? 0;
  if (depth > ACT_MAX_BATCH_DEPTH) {
    throw new Error(`Batch nesting depth exceeds maximum of ${ACT_MAX_BATCH_DEPTH}`);
  }
  if (opts.actions.length > ACT_MAX_BATCH_ACTIONS) {
    throw new Error(`Batch exceeds maximum of ${ACT_MAX_BATCH_ACTIONS} actions`);
  }
  const results: Array<{ ok: boolean; error?: string }> = [];
  for (const action of opts.actions) {
    if (opts.signal?.aborted) {
      throw opts.signal.reason ?? new Error("aborted");
    }
    try {
      await executeSingleAction(
        action,
        opts.cdpUrl,
        opts.targetId,
        opts.evaluateEnabled,
        opts.ssrfPolicy,
        opts.browserProxyMode,
        depth,
        opts.signal,
      );
      results.push({ ok: true });
    } catch (err) {
      if (isBrowserObservedDialogBlockedError(err)) {
        throw err;
      }
      const message = formatErrorMessage(err);
      results.push({ ok: false, error: message });
      if (opts.stopOnError !== false) {
        break;
      }
    }
  }
  return { results };
}

function toLintErrorObject(value: unknown, fallbackMessage: string): Error {
  if (value instanceof Error) {
    return value;
  }
  if (typeof value === "string") {
    return new Error(value);
  }
  const error = new Error(fallbackMessage, { cause: value });
  if ((typeof value === "object" && value !== null) || typeof value === "function") {
    Object.assign(error, value);
  }
  return error;
}
