/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/browser/ssrf-policy-helpers.ts
/**
 * SSRF policy helpers for Browser routes that need one-off hostname grants.
 */
import { uniqueStrings } from "../../../../shim/string-coerce-runtime.js";
import type { SsrFPolicy } from "../infra/net/ssrf.js";

/** Returns an SSRF policy with the hostname added to allowedHostnames. */
export function withAllowedHostname(
  ssrfPolicy: SsrFPolicy | undefined,
  hostname: string,
): SsrFPolicy {
  return {
    ...ssrfPolicy,
    allowedHostnames: uniqueStrings([...(ssrfPolicy?.allowedHostnames ?? []), hostname]),
    // A one-off grant must grant through BOTH policy fields: exact-host trust
    // (allowedHostnames) and, when a strict hostnameAllowlist is active, the
    // allowlist match itself. Otherwise a per-start proxyAllowedHostnames
    // blocks the browser's own loopback CDP endpoint, and every proxied
    // navigation fails before it starts. An absent/empty allowlist stays
    // empty: it means "no allowlist", not "allow only this host".
    ...(ssrfPolicy?.hostnameAllowlist?.length
      ? { hostnameAllowlist: uniqueStrings([...ssrfPolicy.hostnameAllowlist, hostname]) }
      : {}),
  };
}
