import type { Theme } from '../types';

/*
 * Atom One Light — VSCode 经典亮色主题,签名是温柔的 off-white 底 (#FAFAFA) +
 * 函数蓝 accent (#4078F2)。色板取自
 * https://github.com/akamud/vscode-theme-onelight 的官方 OneLight.json。
 *
 * 这是项目里第一个非默认 light 主题,所有 light 默认值已经接近 Atom One Light,
 * 主要差异在 accent (默认是近黑灰,这里换成蓝色) 和 surface (默认 #f8f8f6
 * 偏暖,这里换成 #FAFAFA 偏中性)。
 */
// 既有分组/对比度/否决依据：docs/design-rules/design-decision-log.md
// 「2026-09-11 DS-8 内置主题依据迁移」→ atom-one-light（生成区外保留）。
// BEGIN GENERATED DS-8: theme
const GENERATED_OVERRIDES = {
  "surface": "#FAFAFA",
  "surface-hsl": "0 0% 98%",
  "surface-elevated": "#FFFFFF",
  "surface-elevated-soft": "#EAEAEB",
  "surface-card-ivory": "#FFFFFF",
  "surface-chip": "#EAEAEB",
  "surface-chip-alt": "#EAEAEB",
  "surface-hover": "#E4E4E5",
  "surface-hover-soft": "#FAFAFA",
  "surface-hover-hsl": "240 2% 89%",
  "surface-on-card": "#FFFFFF",
  "border-default": "#D4D4D5",
  "border-default-hsl": "240 2% 83%",
  "border-shadcn-hsl": "240 2% 83%",
  "border-transparent-mixed": "transparent",
  "text-primary": "#383A42",
  "text-primary-on-dark": "#383A42",
  "text-primary-emphasis": "#383A42",
  "text-primary-inv": "#383A42",
  "text-primary-body-strong": "#383A42",
  "text-primary-hsl": "224 8% 24%",
  "text-secondary": "#696c77",
  "text-secondary-cross": "#696c77",
  "text-secondary-mid": "#696c77",
  "text-tertiary": "#A0A1A7",
  "text-tertiary-stone": "#A0A1A7",
  "text-tertiary-mid": "#A0A1A7",
  "text-tertiary-hsl": "228 4% 64%",
  "text-disabled": "#C8C8C9",
  "text-disabled-tertiary": "#C8C8C9",
  "accent-cta-bg": "#4078F2",
  "accent-cta-bg-pure": "#4078F2",
  "accent-emphasis": "#4078F2",
  "accent-soft": "#2050c0",
  "accent-hover": "#2050c0",
  "accent-pure-cta-fg": "#FFFFFF",
  "switch-track-on": "#4078F2",
  "accent": "240 2% 89%",
  "agent-actions-rail": "#D4D4D5",
  "ask-checkbox-border": "#A0A1A7",
  "background": "0 0% 98%",
  "create-agent-control-bg": "#FAFAFA",
  "create-agent-control-bg-hover": "#E4E4E5",
  "create-agent-control-bg-pressed": "#E4E4E5",
  "create-agent-control-border": "#D4D4D5",
  "create-agent-control-icon": "#383A42",
  "create-agent-control-text": "#383A42",
  "create-agent-quick-card-bg": "#FAFAFA",
  "create-agent-quick-card-bg-hover": "#E4E4E5",
  "create-agent-quick-card-border": "#D4D4D5",
  "create-agent-quick-card-icon": "#383A42",
  "create-agent-quick-card-icon-bg": "#EAEAEB",
  "create-agent-quick-card-text": "#383A42",
  "create-agent-segment-inactive-text": "#696c77",
  "create-agent-segment-track-bg": "#FAFAFA",
  "send-btn-bg": "#FAFAFA",
  "send-btn-icon": "#383A42",
  "chat-input-chip-border": "#D4D4D5",
  "chat-input-text": "#383A42",
  "color-primary": "#383A42",
  "confirm-bg": "#FFFFFF",
  "confirm-btn-primary-bg": "#4078F2",
  "confirm-btn-primary-text": "#FFFFFF",
  "confirm-btn-secondary-border": "#D4D4D5",
  "confirm-btn-secondary-hover": "rgba(0, 0, 0, 0.06)",
  "confirm-btn-secondary-text": "#383A42",
  "confirm-title": "#383A42",
  "drop-overlay-bg": "rgba(64, 120, 242, 0.1)",
  "file-chip-bg": "#EAEAEB",
  "file-remove-bg": "#A0A1A7",
  "info-700": "#2050c0",
  "model-trigger-hover": "#E4E4E5",
  "msg-link": "#4078F2",
  "msg-scrollbar-hover": "#A0A1A7",
  "muted": "240 2% 92%",
  "muted-foreground": "220 6% 44%",
  "perm-allow-btn-bg": "#4078F2",
  "perm-allow-btn-text": "#FFFFFF",
  "perm-allow-kbd-bg": "#EAEAEB",
  "perm-allow-kbd-border": "#D4D4D5",
  "perm-code-bg": "#EAEAEB",
  "perm-item-selected-bg": "#EAEAEB",
  "plan-outline-active-bg": "#EAEAEB",
  "plan-toolbar-btn-hover-bg": "#E4E4E5",
  "popover": "0 0% 100%",
  "primary-foreground": "0 0% 100%",
  "search-match-fg": "224 8% 24%",
  "secondary": "240 2% 92%",
  "settings-btn-primary-text": "#FFFFFF",
  "settings-btn-secondary-hover-bg": "#E4E4E5",
  "text-placeholder": "#C8C8C9",
  "settings-integration-avatar-bg": "#EAEAEB",
  "settings-logout-bg": "#EAEAEB",
  "settings-menu-bg-hover": "#E4E4E5",
  "settings-menu-bg-selected": "#EAEAEB",
  "settings-source-link": "#4078F2",
  "settings-theme-auto-dark": "#FAFAFA",
  "sidebar-action-icon": "228 4% 64%",
  "sidebar-item-active": "240 2% 92%",
  "splash-bg": "0 0% 98%",
  "splash-text": "220 6% 44%",
  "splash-text-destructive": "224 8% 24%",
  "splash-text-muted": "228 4% 64%",
  "titlebar-icon": "220 6% 44%",
  "tooltip-bg": "#383A42",
  "tooltip-text": "#FAFAFA",
  "update-btn-border": "#4078F2",
  "update-btn-text": "#4078F2",
} as const;
// END GENERATED DS-8: theme



export const atomOneLight: Theme = {
  id: 'atom-one-light',
  name: 'Atom One Light',
  type: 'light',
  colors: GENERATED_OVERRIDES,
};
