import type { Theme } from '../types';

/*
 * Material Theme Ocean High Contrast — Material Ocean 的高对比变体,极深
 * 蓝灰底 (#0F111A) + 高亮文本 (#EEFFFF) + 标志性 teal accent (#80CBC4)。
 * 色板取自 https://material-theme.com/docs/reference/color-palette/ 的
 * Oceanic 主调,按 high-contrast 规则把 surface 压更深、文本提更亮。
 */
// 既有分组/对比度/否决依据：docs/design-rules/design-decision-log.md
// 「2026-09-11 DS-8 内置主题依据迁移」→ material-ocean-hc（生成区外保留）。
// BEGIN GENERATED DS-8: theme
const GENERATED_OVERRIDES = {
  "surface": "#0F111A",
  "surface-hsl": "231 26% 8%",
  "surface-elevated": "#090B10",
  "surface-elevated-soft": "#090B10",
  "surface-card-ivory": "#090B10",
  "surface-chip": "#1F2233",
  "surface-chip-alt": "#1F2233",
  "surface-hover": "#1A1C25",
  "surface-hover-soft": "#1A1C25",
  "surface-hover-hsl": "228 19% 12%",
  "surface-on-card": "#0F111A",
  "border-default": "#2A2F45",
  "border-default-hsl": "229 25% 22%",
  "border-shadcn-hsl": "229 25% 22%",
  "border-transparent-mixed": "#2A2F45",
  "text-primary": "#EEFFFF",
  "text-primary-on-dark": "#EEFFFF",
  "text-primary-emphasis": "#EEFFFF",
  "text-primary-inv": "#EEFFFF",
  "text-primary-body-strong": "#EEFFFF",
  "text-primary-hsl": "180 100% 97%",
  "text-secondary": "#A6ACCD",
  "text-secondary-cross": "#A6ACCD",
  "text-secondary-mid": "#A6ACCD",
  "text-tertiary": "#717CB4",
  "text-tertiary-stone": "#717CB4",
  "text-tertiary-mid": "#717CB4",
  "text-tertiary-hsl": "226 31% 57%",
  "text-disabled": "#464B5D",
  "text-disabled-tertiary": "#464B5D",
  "accent-cta-bg": "#80CBC4",
  "accent-cta-bg-pure": "#80CBC4",
  "accent-emphasis": "#80CBC4",
  "accent-soft": "#B2DFDB",
  "accent-hover": "#26A69A",
  "accent-pure-cta-fg": "#0F111A",
  "switch-track-on": "#80CBC4",
  "accent": "228 19% 12%",
  "agent-actions-rail": "#2A2F45",
  "ask-checkbox-border": "#464B5D",
  "background": "231 26% 8%",
  "create-agent-control-bg": "#0F111A",
  "create-agent-control-bg-hover": "#1A1C25",
  "create-agent-control-bg-pressed": "#1F2233",
  "create-agent-control-border": "#2A2F45",
  "create-agent-control-icon": "#EEFFFF",
  "create-agent-control-text": "#EEFFFF",
  "create-agent-quick-card-bg": "#0F111A",
  "create-agent-quick-card-bg-hover": "#1A1C25",
  "create-agent-quick-card-border": "#2A2F45",
  "create-agent-quick-card-icon": "#EEFFFF",
  "create-agent-quick-card-icon-bg": "#2A2F45",
  "create-agent-quick-card-text": "#EEFFFF",
  "create-agent-segment-inactive-text": "#717CB4",
  "create-agent-segment-track-bg": "#0F111A",
  "send-btn-bg": "#EEFFFF",
  "send-btn-icon": "#0F111A",
  "chat-input-chip-border": "#2A2F45",
  "chat-input-text": "#EEFFFF",
  "color-primary": "#EEFFFF",
  "confirm-bg": "#090B10",
  "confirm-btn-primary-bg": "#80CBC4",
  "confirm-btn-primary-text": "#0F111A",
  "confirm-btn-secondary-border": "#2A2F45",
  "confirm-btn-secondary-hover": "rgba(255, 255, 255, 0.06)",
  "confirm-btn-secondary-text": "#EEFFFF",
  "confirm-title": "#EEFFFF",
  "drop-overlay-bg": "rgba(128, 203, 196, 0.1)",
  "file-chip-bg": "#2A2F45",
  "file-remove-bg": "#464B5D",
  "info-700": "#B2DFDB",
  "model-trigger-hover": "#1A1C25",
  "msg-link": "#B2DFDB",
  "msg-scrollbar-hover": "#464B5D",
  "muted": "229 25% 16%",
  "muted-foreground": "228 33% 73%",
  "perm-allow-btn-bg": "#80CBC4",
  "perm-allow-btn-text": "#0F111A",
  "perm-allow-kbd-bg": "#1F2233",
  "perm-allow-kbd-border": "#2A2F45",
  "perm-code-bg": "#0F111A",
  "perm-item-selected-bg": "#1F2233",
  "plan-outline-active-bg": "#1F2233",
  "plan-toolbar-btn-hover-bg": "#1A1C25",
  "popover": "226 28% 5%",
  "primary-foreground": "231 26% 8%",
  "search-match-fg": "180 100% 97%",
  "secondary": "226 28% 5%",
  "settings-btn-primary-text": "#0F111A",
  "settings-btn-secondary-hover-bg": "#1A1C25",
  "text-placeholder": "#464B5D",
  "settings-integration-avatar-bg": "#1F2233",
  "settings-logout-bg": "#1F2233",
  "settings-menu-bg-hover": "#1A1C25",
  "settings-menu-bg-selected": "#1F2233",
  "settings-source-link": "#B2DFDB",
  "settings-theme-auto-dark": "#0F111A",
  "sidebar-action-icon": "226 31% 57%",
  "sidebar-item-active": "229 25% 16%",
  "splash-bg": "231 26% 8%",
  "splash-text": "228 33% 73%",
  "splash-text-destructive": "180 100% 97%",
  "splash-text-muted": "226 31% 57%",
  "titlebar-icon": "228 33% 73%",
  "tooltip-bg": "#0F111A",
  "tooltip-text": "#EEFFFF",
  "update-btn-border": "#80CBC4",
  "update-btn-text": "#80CBC4",
} as const;
// END GENERATED DS-8: theme



export const materialOceanHC: Theme = {
  id: 'material-ocean-hc',
  name: 'Material Ocean High Contrast',
  type: 'dark',
  colors: GENERATED_OVERRIDES,
};
